// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJpC9HCYGzLMGQI1EkN3aUZfUrMOer1yk',
    appId: '1:343343266692:web:d699e181918218e7317bd1',
    messagingSenderId: '343343266692',
    projectId: 'sports-app-ef444',
    authDomain: 'sports-app-ef444.firebaseapp.com',
    storageBucket: 'sports-app-ef444.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBARh4aqVh9CdHNAdwfGhKbxdD7k0OX21A',
    appId: '1:343343266692:android:f71289e853d483ef317bd1',
    messagingSenderId: '343343266692',
    projectId: 'sports-app-ef444',
    storageBucket: 'sports-app-ef444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxk64N8Gymi1wqNk9qOrlcQJlTd1vO2FU',
    appId: '1:343343266692:ios:a6a1951ab153c9d2317bd1',
    messagingSenderId: '343343266692',
    projectId: 'sports-app-ef444',
    storageBucket: 'sports-app-ef444.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxk64N8Gymi1wqNk9qOrlcQJlTd1vO2FU',
    appId: '1:343343266692:ios:a6a1951ab153c9d2317bd1',
    messagingSenderId: '343343266692',
    projectId: 'sports-app-ef444',
    storageBucket: 'sports-app-ef444.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJpC9HCYGzLMGQI1EkN3aUZfUrMOer1yk',
    appId: '1:343343266692:web:a853187195755e05317bd1',
    messagingSenderId: '343343266692',
    projectId: 'sports-app-ef444',
    authDomain: 'sports-app-ef444.firebaseapp.com',
    storageBucket: 'sports-app-ef444.firebasestorage.app',
  );
}
